# Generated by Django 6.0.4 on 2026-04-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('candidates', '0002_candidateprofile'),
        ('jobs', '0003_job_job_type_job_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('candidate', 'job')},
        ),
    ]
