# Generated by Django 4.2.28 on 2026-03-22 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit Indian mobile number.', regex='^[6-9]\\d{9}$')])),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('candidate', 'Candidate'), ('hr', 'HR')], max_length=20)),
            ],
        ),
    ]
